https://developer.apple.com/documentation/swift/range

https://docs.swift.org/swift-book/documentation/the-swift-programming-language/



### Строки

```swift
var name = "Anna"
var surname = "Sonn"
var fullName = name + " " + surname

let newInformation = "\(fullName) is the CEO of Apple"
```





### switch

```swift
var animal = "dove"

switch animal {
case "cat":
    print("it's a cat")
case "parrot", "dove", "sparrow", "bird":
    print("it's a bird")
default:
    print("I don't know this kind of animal")
}

let numberOfPeople = 5
var amount = ""

switch numberOfPeople {
case ..<0:
    print("it's impossible!")
case 0:
    amount = "no"
case 1:
    amount = "one"
case 2...5:
    amount = "few"
case 6..<10:
    amount = "enough"
default:
    amount = "too many"
}
```



### Циклы

```swift
for num in 1...5 {
    print(num)
}

for bird in ["parrot", "dove", "sparrow", "bird"] {
    print(bird)
}

let childrenCount = ["Johnsons": 4, "Simpsons": 3, "Jacksons": 8]
for (family, childrenCount) in childrenCount {
    print("The \(family) have \(childrenCount) children")
}
for family in childrenCount.keys {}
for count in childrenCount.values {}

for character in "Hello, world!" {
    print(character)
}
```



### guard

```swift
// Для выхода из функций
func checkUser(username: String, password: String) {
    guard username != "" else { return }
    guard password != "" else { return }
    print("Welcome to our site!")
}

// Для прерывания циклов
for number in 1...5 {
    guard number != 3 else { break }
    print(number)
}


var temp: Int?
temp = 25

func checkTemp(temp: Int?) {
    guard let temp = temp else { return }
    print("The temperature is \(temp) degrees")
}
```





### Псевдонимы типов

```swift
typealias Centigrade = Int

let temperature: Centigrade = 25
let anotherTemp = 20
let difference = temperature - anotherTemp

typealias CompletionHandler = (Int, String) -> String
func someFunc(closure: CompletionHandler) {
    let result = closure(42, "Hello, world!")  // Вызываем переданное замыкание
    print(result) 
}

someFunc { (number, message) in
    return "Number: \(number), Message: \(message)"
}
```



#### Обработка ошибок

```swift
struct Printer {
    var paper: Bool
    var toner: Bool
}

enum PrintingErrors: Error {
    case noPaper
    case noToner
}

func printDocument(on printer: Printer) throws {
    guard printer.paper else {
        throw PrintingErrors.noPaper
    }
    
    guard printer.toner else {
        throw PrintingErrors.noToner
    }
    
    print("Документ успешно напечатан!")
}

let printer = Printer(paper: false, toner: true)

do {
    try printDocument(on: printer)
} catch PrintingErrors.noPaper {
    print("Ошибка: добавьте бумагу в принтер!")
} catch PrintingErrors.noToner {
    print("Ошибка: заправьте принтер тонером!")
} catch {
    print("Неизвестная ошибка: \(error)")
}

```

Есть три способа обработки ошибок при вызове функций, которые могут выбрасывать (`throws`) исключения:

- `try` – стандартный способ с `do-catch`
- `try?` – безопасное приведение ошибки в `nil`
- `try!` – принудительное выполнение (краш, если ошибка)
